version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes

    ports:
      - "6370:6379"
    environment:
      - "REDIS_REPLICATION_MODE=mater"
